In [1]:
#Q1
import pandas as pd

data = {
    "Tid": [1,2,3,4,5,6,7,8,9,10],
    "Refund": ["Yes","No","No","Yes","No","No","Yes","No","No","No"],
    "Marital Status": ["Single","Married","Single","Married","Divorced","Married","Divorced","Single","Married","Single"],
    "Taxable Income": ["125K","100K","70K","120K","95K","60K","220K","85K","75K","90K"],
    "Cheat": ["No","No","No","No","Yes","No","No","Yes","No","Yes"]
}

df = pd.DataFrame(data)
df

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No
9   10     No         Single            90K   Yes

In [2]:
#Q2
df.loc[[0,4,7,8]]

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
4    5     No       Divorced            95K   Yes
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No

In [3]:
#Q3
df.iloc[3:8]
df.iloc[4:9, 2:5]
df.iloc[:, 1:4]

  Refund Marital Status Taxable Income
0    Yes         Single           125K
1     No        Married           100K
2     No         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9     No         Single            90K

In [4]:
#Q4
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris(as_frame=True)
df_iris = iris.frame
df_iris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [5]:
#Q5
df_iris = df_iris.drop(index=4)
df_iris = df_iris.drop(columns=df_iris.columns[3])
df_iris

     sepal length (cm)  sepal width (cm)  petal length (cm)  target
0                  5.1               3.5                1.4       0
1                  4.9               3.0                1.4       0
2                  4.7               3.2                1.3       0
3                  4.6               3.1                1.5       0
5                  5.4               3.9                1.7       0
..                 ...               ...                ...     ...
145                6.7               3.0                5.2       2
146                6.3               2.5                5.0       2
147                6.5               3.0                5.2       2
148                6.2               3.4                5.4       2
149                5.9               3.0                5.1       2

[149 rows x 4 columns]

In [6]:
#QQ6
data = {
    "Employee_ID": [101,102,103,104,105],
    "Name": ["Alice","Bob","Charlie","Diana","Edward"],
    "Department": ["HR","IT","IT","Marketing","Sales"],
    "Age": [29,34,41,28,38],
    "Salary": [50000,70000,65000,55000,60000],
    "Years_of_Experience": [4,8,10,3,12],
    "Joining_Date": ["2020-03-15","2017-07-19","2013-06-01","2021-02-10","2010-11-25"],
    "Gender": ["Female","Male","Male","Female","Male"],
    "Bonus": [5000,7000,6000,4500,5000],
    "Rating": [4.5,4.0,3.8,4.7,3.5]
}

df = pd.DataFrame(data)
df.to_csv("employees.csv", index=False)
df

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [7]:
df.shape
df.info()
df.describe()
df.head()
df.tail(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [8]:
df["Salary"].mean()
df["Bonus"].sum()
df["Age"].min()
df["Rating"].max()
df.sort_values("Salary", ascending=False)

df["Performance"] = df["Rating"].apply(lambda x: "Excellent" if x >= 4.5 else "Good" if x >= 4.0 else "Average")
df

df.isnull().sum()
df.rename(columns={"Employee_ID": "ID"}, inplace=True)
df

df[df["Years_of_Experience"] > 5]
df[df["Department"] == "IT"]

df["Tax"] = df["Salary"] * 0.10
df

df.to_csv("modified_employees.csv", index=False)